server:
  port: 8080
  servlet:
    context-path: /ticketServer

spring:
  datasource:
    url: jdbc:mysql://rm-wz9kct6uv12i81u6no.mysql.rds.aliyuncs.com:3306/ticket?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2b8&useSSL=false
    username: kangmeng
    password: Kangmeng*123
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_identifier_rollback: true
        dialect: org.hibernate.dialect.MySQL5Dialect
        hikari:
          dataSource:
            cachePrepStmts:true
            prepStmtCacheSize:250
            prepStmtCacheSqlLimit:2048
            useServerPrepStmts:true
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy:  com.km086.server.config.TableNamingStrategy
  data:
    redis:
      repositories:
        enabled: false
  redis:
    host: r-wz960c2197c9e584800.redis.rds.aliyuncs.com
    port: 6379
    password: Kangmeng2017
    timeout: 10000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

app:
  needPayProcessNum: 10
  noNeedPayProcessNum: 2
  imageDir: /home/images
  apkDir: /home/apk
  superPassword: kangmeng2017@